#spring.application.name=demo
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#server.address=0.0.0.0

spring.application.name=demo

# MySQL connection
#spring.datasource.url=jdbc:mysql://localhost:3306/demo_db
#spring.datasource.username=root
#spring.datasource.password=rama7222
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://root:lojTPuFmCDQtsaPYTcjNfEfoCxdzQSqN@switchback.proxy.rlwy.net:54122/railway
spring.datasource.username=root
spring.datasource.password=lojTPuFmCDQtsaPYTcjNfEfoCxdzQSqN

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.address=0.0.0.0

server.port=${PORT:8080}

spring.security.user.name=admin
spring.security.user.password=admin7222

jwt.secret=mysupersecuresecretkeymysupersecuresecretkey12345

whatsapp.api.url=https://graph.facebook.com/v19.0
whatsapp.phone.number.id=1088324854356250
whatsapp.access.token=EAAR1O794jYsBQ2BYkKaoSLZBDZCk31tCyCZC3lMznTby9KHMgwm1iFdPtGsiNFKC8CKqXJpkZAzmfwQy7mj8ZABAbyvtHKwFGZCzBRZBZAuB6viSKNiM3VY0TGH8w4UX5kURi2gpuCFZC9dVtee2FgiL68uV8XnGZBZALgfZC96xtHtpDmKW8y2V8od7dgw9hhMdPpVeSea2Djr9u0iMEz8H2msGfDrwmp02u4iXS61LdvZC2Hmitjvk5NXFhzcC7kd5fH5tGEkY885HZBdw0ZCFZCfb1a85FDSt

